name: test

on: [push]

jobs:
  linux-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pytest and mockwalkers
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .
      - name: Test with pytest
        run: |
          pytest